# Generated by Django 4.1.6 on 2023-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes', to='kitchen.ingredient'),
        ),
    ]
